import { NgModule } from '@angular/core';
import {
	MatAutocompleteModule,
	MatButtonModule,
	MatButtonToggleModule,
	MatCardModule,
	MatCheckboxModule,
	MatChipsModule,
	MatDatepickerModule,
	MatDialogModule,
	MatExpansionModule,
	MatFormFieldModule,
	MatIconModule,
	MatInputModule,
	MatListModule,
	MatNativeDateModule,
	MatOptionModule,
	MatProgressBarModule,
	MatRadioModule,
	MatSelectModule,
	MatStepperModule,
	MatTabsModule,
} from '@angular/material';

@NgModule({
	imports: [
		MatButtonModule,
		MatIconModule,
		MatCardModule,
		MatFormFieldModule,
		MatInputModule,
		MatListModule,
		MatDatepickerModule,
		MatNativeDateModule,
		MatSelectModule,
		MatOptionModule,
		MatCheckboxModule,
		MatRadioModule,
		MatDialogModule,
		MatAutocompleteModule,
		MatProgressBarModule,
	],
	exports: [
		MatButtonModule,
		MatIconModule,
		MatCardModule,
		MatFormFieldModule,
		MatInputModule,
		MatListModule,
		MatDatepickerModule,
		MatNativeDateModule,
		MatSelectModule,
		MatOptionModule,
		MatCheckboxModule,
		MatRadioModule,
		MatButtonToggleModule,
		MatDialogModule,
		MatAutocompleteModule,
		MatStepperModule,
		MatExpansionModule,
		MatTabsModule,
		MatChipsModule,
		MatProgressBarModule,
	],
})
export class MaterialModule {}
